server:
  port: 8000
spring:
  application:
    name: microservice-provider-user
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@192.168.1.170:8761/eureka/,http://user:password123@192.168.1.170:8762/eureka/
  instance:
    prefer-ip-address: true
    #hostname: ${spring.cloud.client.ipAddress}
    #instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-expiration-duration-in-seconds: 5 #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-renewal-interval-in-seconds: 10 #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）