security:
  basic:
    enabled: true               # 开启基于HTTP basic的认证
  user:
    name: user                  # 配置登录的账号是user
    password: password123       # 配置登录的密码是password123
spring:
  application:
    name: discovery-eureka-ha
---
spring:
  profiles: peer1                                 # 指定profile=peer1
server:
  port: 8761
eureka:
  server:
    use-read-only-response-cache: false  #禁用服务缓存
    enable-self-preservation: false  #关闭保护机制
    eviction-interval-timer-in-ms: 200 #剔除失效服务间隔
  instance:
    hostname: peer1                               # 指定当profile=peer1时，主机名是peer1
  client:
    serviceUrl:
      defaultZone: http://user:password123@127.0.0.1:8762/eureka/      # 将自己注册到peer2这个Eureka上面去
    fetch-registry: false

---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  server:
    use-read-only-response-cache: false  #禁用服务缓存
    enable-self-preservation: false  #关闭保护机制
    eviction-interval-timer-in-ms: 200 #剔除失效服务间隔
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://user:password123@127.0.0.1:8761/eureka/
    fetch-registry: false