server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
     com.itmuch.cloud.study.user.feign.UserFeignClient: DEBUG
feign:
  client:
    config:
      microservice-provider-user:
        loggerLevel: full