server:
  port: 8011
spring:
  application:
    name: microservice-consumer-movie
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@192.168.1.170:8761/eureka/
  instance:
    prefer-ip-address: true